/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "handshake.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(m2s_MDR_request, m2s_MDR_request, AUTO)


PB_BIND(s2m_MDR_req_ACK, s2m_MDR_req_ACK, AUTO)


PB_BIND(m2s_MDR_res_CTS, m2s_MDR_res_CTS, AUTO)


PB_BIND(_subscriptions, _subscriptions, AUTO)


PB_BIND(s2m_MDR_response, s2m_MDR_response, AUTO)



